C84J-16: Change lon and lat to Double
Macrometacorp/c84j pull request #131
Opened 2023-10-11 03:26 UTC by dlazarenko-macrometa

Changed the longitute and latitude fields in response of GET `/datacenter/local` from `String` to `Double`.

2023-10-11 04:48 UTC, yehan-macrometa requested changes

2023-10-11 04:48 UTC, yehan-macrometa commented on src/main/java/com/c8db/entity/DcInfoEntity.java
> +        public Double getLatitude() {
@dlazarenko-macrometa - Why cannot we use Lombok getters?

2023-10-11 04:48 UTC, yehan-macrometa commented on src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java
> +                    vpack.get("countryname").getAsString(),
@dlazarenko-macrometa - In the `LocationInfo` class, we have `countryCode` and `countryName` in camel case. Here we have all simple case. Would this be an issue?

2023-10-11 04:48 UTC, yehan-macrometa commented on src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java
> +            String lon = vpack.get("latitude").getAsString();
```suggestion
            String lon = vpack.get("longitude").getAsString();
```

2023-10-11 20:06 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java
> +                    vpack.get("countryname").getAsString(),
@yehan-macrometa  - These parameters are in lowercase in API. So, there should be no issues.

2023-10-11 20:07 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/entity/DcInfoEntity.java
> +        public Double getLatitude() {
Changed

2023-10-11 20:07 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/internal/velocypack/VPackDeserializers.java
> +            String lon = vpack.get("latitude").getAsString();
Changed

2023-10-12 03:21 UTC, StoyanTc approved these changes

2023-10-12 06:20 UTC, yehan-macrometa approved these changes

2023-10-12 13:09 UTC, merged