CEP-187 Added implementation for tenant-metrics API
Macrometacorp/c84j pull request #27
Opened 2022-01-10 10:01 UTC by arpitamishra-macrometa

This pull request contains the implementation for extending c84j library with tenant-metrics API (URL: {base-url}/_fabric/{fabric}/_api/metrics/query.

2022-01-10 11:08 UTC, grainier-macrometa requested changes

2022-01-10 11:08 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +        //Finalize defaults of TenantMetricsOption with Stoyan
Let's make this a TODO, by adding `// TODO: `at the beginning.

2022-01-10 11:08 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +    protected Request getTenantMetricsRequest(final String tenant, TenantMetricsOption options){
`final String tenant` Seems redundant.

2022-01-10 17:13 UTC, StoyanTc requested changes

2022-01-10 17:13 UTC, StoyanTc commented on src/main/java/com/c8db/entity/MetricsEntity.java
> +
Can you please make this class nested for TenantMetricsEntity? It won't be used anywhere else.

2022-01-10 17:13 UTC, StoyanTc commented on src/main/java/com/c8db/internal/C8AdminImpl.java
> +		TenantMetricsEntity tenantMetrics = C8Mapper.mapTenantMetrics(result);
Please change the `getTenantMetricResponseDeserializer()` to return straight an object of `TenantMetricsEntity` and get rid of `C8mapper`?

You could refer to `getTenantLimitsResponseDeserializer()` implementation.

2022-01-10 17:13 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +        //Finalize defaults of TenantMetricsOption with Stoyan
And you might avoid my name into the comment as well? :)

2022-01-11 05:30 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Admin.java
> +import com.c8db.entity.*;
Added single imports as suggested. Changes will be pushed with next commit.

2022-01-11 05:33 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/MetricsEntity.java
> +package com.c8db.entity;
Added copyright information in the newly added classes. Changes will be pushed with next commit.

2022-01-11 05:51 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Admin.java
> +    TenantMetricsEntity getTenantMetrics(final String tenant, TenantMetricsOption options) throws C8DBException, JsonProcessingException;
Implemented.

2022-01-11 05:59 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/C8AdminImpl.java
> +import com.c8db.entity.*;
Implemented.

2022-01-11 05:59 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +        System.out.println("Building response....");
Removed println.

2022-01-11 06:02 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +        //Finalize defaults of TenantMetricsOption with Stoyan
Implemented.

2022-01-11 06:02 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +    protected Request getTenantMetricsRequest(final String tenant, TenantMetricsOption options){
Resolved.

2022-01-11 06:07 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/MetricsEntity.java
> +
Implemented.

2022-01-11 06:52 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/C8AdminImpl.java
> +		TenantMetricsEntity tenantMetrics = C8Mapper.mapTenantMetrics(result);
Implemented.

2022-01-11 06:58 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +        System.out.println("Building response....");
`println` is still there, right?

2022-01-11 07:14 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +        System.out.println("Building response....");
Fixed.

2022-01-11 08:59 UTC, StoyanTc commented on src/main/java/com/c8db/C8Admin.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
@arpitamishra-macrometa - Please get rid of unused import.

2022-01-11 08:59 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +                return tenantMetrics;
@arpitamishra-macrometa - Won't it work here the following construct:
```
TenantMetricsEntity tenantMetrics =  util().deserialize(result,  new Type<TenantMetricsEntity >(){}.getType());```

Do you really need to map the response twice - first to `String` and then to `TenantMetricsEntity `?

2022-01-11 09:29 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +                return tenantMetrics;
I tried this way earlier , but this won't work as the response contains the value against key "c8cep_app_throughput_total" and "c8cep_app_latency_seconds_sum" nested inside "results" . Hence I have added this extra processing logic.

2022-01-11 09:31 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +                return tenantMetrics;
ok, @arpitamishra-macrometa I'll give a try too a bit later.

2022-01-11 09:44 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Admin.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
Removed used import for JsonProcessingException

2022-01-11 09:57 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +                return tenantMetrics;
@arpitamishra-macrometa - Can you please try once again using annotation of the real fields' names, e.g.
```
public class TenantMetricsEntity implements Entity {
        @SerializedName("c8cep_app_throughput_total")
        List<MetricsEntity> throughput;
        @SerializedName("c8cep_app_latency_seconds_sum")
        List<MetricsEntity> latencySum;
        ....
```

2022-01-12 09:54 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Admin.java
> +                return tenantMetrics;
This implementation didn't work as well.

2022-01-12 10:24 UTC, StoyanTc approved these changes

2022-01-12 11:11 UTC, grainier-macrometa approved these changes

2022-01-12 12:34 UTC, merged