Dynamo Support
Macrometacorp/c84j pull request #49
Opened 2022-03-22 08:56 UTC by arpitamishra-macrometa

This PR contains implementation of APIs for dynamo like collections

2022-03-22 10:50 UTC, grainier-macrometa commented on src/main/java/com/c8db/C8Database.java
> +    C8Dynamo dynamo(final String tableName);
@arpitamishra-macrometa - Since these are APIs, let's add method descriptions.

2022-03-22 10:53 UTC, grainier-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +     * @throws C8DBException
@arpitamishra-macrometa - `@params` are not captured in the description.

2022-03-22 10:56 UTC, grainier-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +    //JSONObject putItem(JSONObject options) throws C8DBException;
@arpitamishra-macrometa - Do we need this here?

2022-03-22 10:58 UTC, grainier-macrometa commented on src/main/java/com/c8db/entity/BaseKeyValue.java
> +
@arpitamishra-macrometa - Let's get rid of these additional lines.

2022-03-22 10:58 UTC, grainier-macrometa commented on src/main/java/com/c8db/entity/C8DynamoDeleteEntity.java
> +package com.c8db.entity;
@arpitamishra-macrometa - Let's add the copyright header here as well.

2022-03-22 10:59 UTC, grainier-macrometa commented on src/main/java/com/c8db/entity/C8DynamoDeleteEntity.java
> +   C8DynamoTableDescription TableDescription;
@arpitamishra-macrometa - Small indentation issue.

2022-03-22 11:00 UTC, grainier-macrometa commented on src/main/java/com/c8db/entity/C8DynamoItemEntity.java
> +    Map<String,Map<String,Object>> LastEvaluatedKey;
@arpitamishra-macrometa - Let's have whitespace after the `,`.

2022-03-22 11:01 UTC, grainier-macrometa commented on src/main/java/com/c8db/entity/C8DynamoItemEntity.java
> +    public C8DynamoItemEntity(){super();}
@arpitamishra-macrometa - Let's move this to a separate line and indent it properly.

2022-03-22 11:02 UTC, grainier-macrometa commented on src/main/java/com/c8db/entity/C8KVEntity.java
> +	public C8KVEntity() {
@arpitamishra-macrometa - Let's fix this indentation issue as well.

2022-03-22 11:03 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/C8DynamoImpl.java
> +package com.c8db.internal;
@arpitamishra-macrometa - Missing copyright header.

2022-03-22 11:04 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/C8DynamoImpl.java
> +import com.c8db.entity.*;
@arpitamishra-macrometa - Let's add single imports here.

2022-03-22 11:05 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/C8KeyValueImpl.java
> +import com.c8db.entity.*;
@arpitamishra-macrometa - Let's add single imports here as well.

2022-03-22 11:06 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/C8KeyValueImpl.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(C8KeyValue.class);
@arpitamishra-macrometa - The logger class should be `C8KeyValueImpl`.

2022-03-22 11:06 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +import java.util.*;
@arpitamishra-macrometa - Let's add single imports here as well.

2022-03-22 11:07 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +    public D db() {
@arpitamishra-macrometa - There should be an empty line before the construct.

2022-03-22 11:10 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        request.putHeaderParam("X-Amz-Target","DynamoDB_20120810.CreateTable");
@arpitamishra-macrometa - Shall we make these header parameters into constants? And move it to a single place.

2022-03-22 11:11 UTC, grainier-macrometa commented on src/main/java/com/c8db/internal/InternalC8KeyValue.java
> +import java.util.*;
@arpitamishra-macrometa - Let's use single imports here as well.

2022-03-22 11:12 UTC, grainier-macrometa commented on src/main/java/com/c8db/model/C8DynamoCreateOptions.java
> +package com.c8db.model;
@arpitamishra-macrometa - Missing copyright header.

2022-03-22 11:14 UTC, grainier-macrometa approved these changes
@arpitamishra-macrometa - Added a few comments. Other that LGTM.

2022-03-23 06:20 UTC, StoyanTc requested changes
1. The KV sources are outdated, please merge again my branch
1. Please correct the return values of your interface methods;
2. Please fix all comments of Grainier nevertheless he has approved the PR

2022-03-23 06:20 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +    protected Request createDeleteRequest(final String tableName,final C8DynamoCreateOptions options) {
@arpitamishra-macrometa - Please leave a space after the comma.

2022-03-23 06:20 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +    private static final String OLD = "old";
@arpitamishra-macrometa - Where do you use the both constants?

2022-03-23 06:20 UTC, StoyanTc commented on src/main/java/com/c8db/internal/C8DynamoImpl.java
> +        return executor.execute(createDeleteRequest(tableName,options),
@arpitamishra-macrometa - Please always leave a space after the comma. There are many such places in your code.

2022-03-23 07:32 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Database.java
> +    C8Dynamo dynamo(final String tableName);
Implemented

2022-03-23 07:34 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +     * @throws C8DBException
Implemented

2022-03-23 07:36 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +    //JSONObject putItem(JSONObject options) throws C8DBException;
Removed

2022-03-23 08:18 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/C8DynamoDeleteEntity.java
> +package com.c8db.entity;
Done

2022-03-23 08:18 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/BaseKeyValue.java
> +
Removed

2022-03-23 08:21 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/C8DynamoDeleteEntity.java
> +   C8DynamoTableDescription TableDescription;
@grainier-macrometa Can you tell what's the issue ? I don't see any indentation problem here.

2022-03-23 08:22 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/C8DynamoItemEntity.java
> +    Map<String,Map<String,Object>> LastEvaluatedKey;
Done

2022-03-23 08:22 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/C8DynamoItemEntity.java
> +package com.c8db.entity;
Added

2022-03-23 08:23 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/C8DynamoItemEntity.java
> +    public C8DynamoItemEntity(){super();}
Corrected

2022-03-23 08:23 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/C8DynamoImpl.java
> +package com.c8db.internal;
Added

2022-03-23 08:27 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/C8DynamoImpl.java
> +import com.c8db.entity.*;
Done

2022-03-23 08:28 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/C8KeyValueImpl.java
> +import com.c8db.entity.*;
Done

2022-03-23 08:29 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/C8KeyValueImpl.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(C8KeyValue.class);
Corrected

2022-03-23 08:32 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +import java.util.*;
Done

2022-03-23 08:33 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +    public D db() {
Done

2022-03-23 08:35 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8KeyValue.java
> +import java.util.*;
Done

2022-03-23 08:35 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/model/C8DynamoCreateOptions.java
> +package com.c8db.model;
Added

2022-03-23 08:37 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +    private static final String OLD = "old";
These are not used. I have removed those.

2022-03-23 08:39 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/C8DynamoImpl.java
> +        return executor.execute(createDeleteRequest(tableName,options),
Noted and corrected.

2022-03-23 08:48 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        request.putHeaderParam("X-Amz-Target","DynamoDB_20120810.CreateTable");
Moved these to a  file  containing all constants..

2022-03-23 12:33 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +    <T> MultiDocumentEntity<C8DynamoItemEntity> putItem(Collection<T> values) throws C8DBException;;
Done

2022-03-23 12:34 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +    <T> MultiDocumentEntity<C8DynamoItemEntity> updateItem(Collection<T> values) throws C8DBException;
Done

2022-03-23 12:35 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +    <T> MultiDocumentEntity<C8DynamoItemEntity> deleteItem(Collection<T> values) throws C8DBException;
Done. The` MultiDocumentEntity<DocumentCreateEntity<T>>` is used for delete and get since there wasn't a need to create separate entity for `DELETE `and `GET`

2022-03-23 12:36 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/C8Dynamo.java
> +    <T> MultiDocumentEntity<C8DynamoItemEntity> getItems(Collection<T> values) throws C8DBException;
Done

2022-03-24 06:28 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/C8KVEntity.java
> +	public C8KVEntity() {
Fixed

2022-03-24 16:31 UTC, StoyanTc requested changes
@arpitamishra-macrometa - Once you've done with the request changes, please try to send a collection of items using the putItem().

2022-03-24 16:31 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        request.putHeaderParam(C8Constants.C8_DYNAMO_HEADER_KEY,C8Constants.C8_DYNAMO_CREATE_TABLE_VAL);
@arpitamishra-macrometa - 
1. Please remove the class C8Constants and add the constants locally.
2. Please put a whitespace after the comma and check the rest of your code for the same.

2022-03-24 16:31 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        System.out.println("Request : " + request.getBody());
@arpitamishra-macrometa - Please get rid of `System.out.println(..`.

2022-03-24 16:31 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        T value = items.next();
@arpitamishra-macrometa - As far as I see your request will put only the first value of the collection and the rest will be skipped.

2022-03-24 16:31 UTC, StoyanTc commented on src/main/java/com/c8db/model/C8DynamoCreateOptions.java
> +package com.c8db.model;
@arpitamishra-macrometa - Please correct the header.

2022-03-24 16:31 UTC, StoyanTc commented on src/main/java/com/c8db/model/C8DynamoCreateOptions.java
> +public class C8DynamoCreateOptions extends CollectionCreateOptions{
@arpitamishra-macrometa - 
1. You have everywhere a whitespace before the curved bracket except here. Let's follow one and the same style.
2. I'm not sure you really need this class.

2022-03-25 05:36 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/entity/C8DynamoDeleteEntity.java
> + *  * Copyright (c) 2022 Macrometa Corp All rights reserved
Corrected

2022-03-25 05:37 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> + */
Corrected

2022-03-25 05:39 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        request.putHeaderParam(C8Constants.C8_DYNAMO_HEADER_KEY,C8Constants.C8_DYNAMO_CREATE_TABLE_VAL);
Done

2022-03-25 05:40 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        System.out.println("Request : " + request.getBody());
I kept that for testing . Removed.

2022-03-25 06:00 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/model/C8DynamoCreateOptions.java
> +public class C8DynamoCreateOptions extends CollectionCreateOptions{
Corrected. Yes I need this class for creating and deleting collection.

2022-03-25 06:05 UTC, arpitamishra-macrometa commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +        T value = items.next();
This is because every time the request body just contains a single value for a collection. To keep it consistent with KV and other doc type implementation I had to implement this way. However, I have corrected the implementation to work on collection of values.

2022-03-29 06:30 UTC, StoyanTc commented on src/main/java/com/c8db/internal/InternalC8Dynamo.java
> +    }
@arpitamishra-macrometa - You don't need an iterator here, there is an overloaded `serialize()` for Collection.
```
request.setBody(util(Serializer.CUSTOM).serialize(values,
                new C8Serializer.Options().serializeNullValues(false).stringAsJson(true)));

2022-03-30 12:26 UTC, StoyanTc approved these changes

2022-03-31 09:30 UTC, merged