Support custom secret providers
Macrometacorp/c84j pull request #65
Opened 2022-06-29 11:01 UTC by praminda-macrometa

Users are now able to provide their own way to retrieve the token to communicate with c8 servers.

2022-06-30 16:27 UTC, dlazarenko-macrometa requested changes

2022-06-30 16:27 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/C8DB.java
> +            HostDescription auxHost = hosts.get(Service.C8DB).get(0);
Better to move this line up to 625 line as in 618-624 lines it adds items to `hosts` map

2022-06-30 16:27 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/internal/C8RemoteSecretProvider.java
> +        this.password = password != null ? password.toCharArray() : "".toCharArray();
What is the purpose to convert `password` to char array and then again converting to string?

2022-06-30 20:16 UTC, StoyanTc reviewed
@praminda-macrometa - How your implementation will work for customer who wants to use his tenant but doesn't know the `_mm` password? Have you made such tests? 
This is the case one decides to use `c84j` as driver.

2022-07-01 07:31 UTC, praminda-macrometa commented
@StoyanTc I'm not sure if I understood your question correctly.
From users perspective nothing has changed from the old implementation. They can provide the same username/password pair and if it worked earlier, this will work too.

2022-07-01 08:58 UTC, praminda-macrometa commented on src/main/java/com/c8db/internal/C8RemoteSecretProvider.java
> +        this.password = password != null ? password.toCharArray() : "".toCharArray();
when keeping passwords in memory its a best practice to use char[] in java. This will make the password unreadable in memory dumps. if you keep it in strings and get a dump, an observer can get the password out in plain text. 

I've made a mistake in the constructor param. that should also be a char[] here. I made that change in a new commit. This change should happen all the way up to driver's builder interface. but that will be an API change we shouldn't do in this minor release. hence skipped that change.

2022-07-01 09:00 UTC, praminda-macrometa commented
@StoyanTc Tenant use case now works when we provide email/password for authentication.

2022-07-01 11:55 UTC, StoyanTc commented on src/main/java/com/c8db/internal/C8RemoteSecretProvider.java
> +        this.password = password != null ? password.toCharArray() : "".toCharArray();
Very good explanation! Thanks @praminda-macrometa 
CC @arpitamishra-macrometa @chandrashekhar-macrometa @grainier-macrometa @yehan-macrometa

2022-07-01 12:25 UTC, praminda-macrometa commented on src/main/java/com/c8db/internal/http/HttpConnection.java
> +        String secret = secretProvider.fetchSecret();
Yes. here its only generating the token. Token renewal happens when we invoke the actual API endpoint for the user's request. Its already implemented around L240-L250

2022-07-07 08:04 UTC, dlazarenko-macrometa requested changes

2022-07-07 08:04 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/internal/http/HttpConnection.java
> +                password(password.toCharArray()).client(client).host(auxHost).serialization(util).build();
`password` could be null 
better to change it to `password != null ? password.toCharArray() : null`

2022-07-07 08:04 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/internal/http/HttpConnection.java
> +        secretProvider.init(secCtx);
should be `this.secretProvider`

2022-07-07 08:04 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/internal/C8RemoteSecretProvider.java
> +        this.password = password != null ? password : "".toCharArray();
i believe it should be `context.password` instead of `password`

2022-07-11 14:43 UTC, StoyanTc approved these changes

2022-07-11 14:47 UTC, grainier-macrometa approved these changes

2022-07-12 08:05 UTC, merged