Provide tenant as input to fetchSecret
Macrometacorp/c84j pull request #70
Opened 2022-07-20 06:36 UTC by praminda-macrometa

Most implementations of SecretProvider requires tenant as input to fetchSecret method. So the tenant for token request can be changed dynamically after initializing the driver.

2022-07-20 07:27 UTC, StoyanTc approved these changes

2022-07-20 08:33 UTC, dlazarenko-macrometa requested changes

2022-07-20 08:33 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/internal/http/HttpConnection.java
> +                addJWT(request.getTenant());
request not always has a tenant. sometimes it is null. Therefore if using j84j for a special username and for request that does not have a tenant then it will throw an exception.

2022-07-20 08:33 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/SecretProvider.java
> +    String fetchSecret(String tenant);
I do not like this approach. First of all, we have already `init(SecretProviderContext context)` where all additional params should be.
Secondly, customers should not have access to another user(with tenant)  at all. Therefore, we should not show any parameter that able to change user like `tenant`

2022-07-20 08:33 UTC, dlazarenko-macrometa commented on src/main/java/com/c8db/SecretProvider.java
> +    String fetchSecret(String tenant);
Please put `tenant` and `username` via `C8InternalSecretProvider` only.

2022-07-20 10:13 UTC, praminda-macrometa commented on src/main/java/com/c8db/internal/http/HttpConnection.java
> +                addJWT(request.getTenant());
if the tenant is null we don't have a way of getting a user/tenant token. Which means the secret provider should/will return the service jwt directly

2022-07-20 10:13 UTC, praminda-macrometa commented on src/main/java/com/c8db/SecretProvider.java
> +    String fetchSecret(String tenant);
1. I dont think tenant is a parameter we can provider when secret provider is initialized. Its only known when c8db instance is being executed.
2. `fetchSecret` is called internally from the `HttpConnection` users cant give different values for this from out side.

2022-07-21 08:13 UTC, dlazarenko-macrometa approved these changes

2022-07-21 09:18 UTC, merged